---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

Emily Maruska: For steps 12.3 everything went smoothly, I didn't have any trouble getting the rmd file to load from github.  For steps 12.4 I did not check the add to md file so I only updated the rmd but not the md, which was a problem but it was easily fixed.

Aidan Bobholz: Following along with step 12.3, I ran into one issue in which I had to restart R in order for the git to register as installed to create new project>git thingy. After restarting R I was able to successfully load in the git repository. Going into step four commiting worked once I realized that you do not need to select sign commit. Step five worked once I had pulled first in order to have my file correctly up to date. After these steps this file had successfully made it from my RStudio and into the github repository.

Ryan Ledbetter: For steps 12.3 everything went smoothly until I had to deal with account issues. My account was setup with a personal account and I had to make changes to my UAC settings in Windows but everything is coolio.

Ryan Riebesehl: Lab report #1 Step 12.2: Fine, did not run into any problems. Was able to copy the link properly. Step 12.3: Fine for the most part, had a confusing part because I accidentally doubled the file under my own git account and not my groups. So I had to delete my previous one. Step 12.4: Fine, was able to save and commit my work to git. Step 12.5: Did not work at first, but had to wait so we all did not do it at the same time. Step 12.6: Was able to see changes on the GitHub repo.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.
